-- AlterTable
ALTER TABLE "KycApplication" ADD COLUMN     "companyName" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "corporateContacts" JSONB NOT NULL DEFAULT '[]',
ADD COLUMN     "economicSector" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "investorCategory" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "jointAnnualIncome" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "jointBusinessAddress" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "jointCity" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "jointDob" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "jointEmail" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "jointEmployerAddress" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "jointEmployerName" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "jointEmploymentStatus" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "jointFullName" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "jointGender" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "jointHouseNumber" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "jointIdExpiryDate" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "jointIdIssueDate" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "jointIdNumber" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "jointIdType" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "jointMaritalStatus" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "jointNationality" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "jointPepDetails" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "jointPepStatus" TEXT NOT NULL DEFAULT 'no',
ADD COLUMN     "jointPhone" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "jointProfession" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "jointRegion" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "jointResidentialStatus" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "jointSourceOfFunds" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "jointSubCity" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "jointTel" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "jointTin" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "jointWoredaKebele" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "registrationDate" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "registrationNumber" TEXT NOT NULL DEFAULT '';

-- CreateTable
CREATE TABLE "TradeOrder" (
    "id" TEXT NOT NULL,
    "orderId" TEXT NOT NULL,
    "clientName" TEXT NOT NULL,
    "idNumber" TEXT NOT NULL,
    "csdAccountNumber" TEXT NOT NULL,
    "symbol" TEXT NOT NULL,
    "side" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "limitPrice" TEXT NOT NULL DEFAULT '',
    "stopPrice" TEXT NOT NULL DEFAULT '',
    "quantity" TEXT NOT NULL DEFAULT '',
    "timeInForce" TEXT NOT NULL,
    "goodTillDate" TEXT NOT NULL DEFAULT '',
    "clientSignature" TEXT NOT NULL DEFAULT '',
    "receivedVia" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'Pending',
    "rejectionReason" TEXT NOT NULL DEFAULT '',
    "traderSignature" TEXT NOT NULL DEFAULT '',
    "receivedBy" TEXT NOT NULL DEFAULT '',
    "dateReceived" TEXT NOT NULL DEFAULT '',
    "timeReceived" TEXT NOT NULL DEFAULT '',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TradeOrder_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "TradeOrder_orderId_key" ON "TradeOrder"("orderId");
