const swaggerJsdoc = require("swagger-jsdoc");

const options = {
  definition: {
    openapi: "3.0.0",
    info: {
      title: "Prime Capital Backend API",
      version: "1.1.0",
      description:
        "KYC (Individual, Corporate, Joint), Trade Orders, and Admin API for Prime Capital S.C.",
      contact: {
        name: "Prime Capital Support",
        email: "compliance@primecapital.et",
      },
    },
    servers: [
      { url: "http://localhost:5000", description: "Development server" },
      { url: "https://dev-api.primecapitalsc.com/", description: "Deployed server" },
    ],
    components: {
      securitySchemes: {
        bearerAuth: {
          type: "http",
          scheme: "bearer",
          bearerFormat: "JWT",
          description: "Enter your JWT token",
        },
      },
      schemas: {
        Error: {
          type: "object",
          properties: { error: { type: "string" } },
        },
        LoginRequest: {
          type: "object",
          required: ["email", "password"],
          properties: {
            email: { type: "string", format: "email", example: "compliance@primecapital.et" },
            password: { type: "string", example: "Admin@12345" },
          },
        },
        LoginResponse: {
          type: "object",
          properties: {
            token: { type: "string" },
            user: { $ref: "#/components/schemas/AdminUser" },
          },
        },
        AdminUser: {
          type: "object",
          properties: {
            id: { type: "string" },
            email: { type: "string", format: "email" },
            name: { type: "string" },
            role: { type: "string", enum: ["compliance_officer", "admin", "super_admin"] },
          },
        },
        CorporateContact: {
          type: "object",
          properties: {
            fullName: { type: "string" },
            faydaId: { type: "string" },
            department: { type: "string" },
            position: { type: "string" },
            email: { type: "string", format: "email" },
            phone: { type: "string" },
          },
        },
        KycDocuments: {
          type: "object",
          properties: {
            faydaFront: { type: "string", nullable: true },
            faydaBack: { type: "string", nullable: true },
            kebeleId: { type: "string", nullable: true },
            drivingLicense: { type: "string", nullable: true },
            companyStamp: { type: "string", nullable: true },
          },
        },
        OfficeUse: {
          type: "object",
          properties: {
            preparedBy: { type: "string" },
            preparedSign: { type: "string" },
            preparedDate: { type: "string" },
            approvedBy: { type: "string" },
            approvedSign: { type: "string" },
            approvedDate: { type: "string" },
            checkedBy: { type: "string" },
            checkedSign: { type: "string" },
            checkedDate: { type: "string" },
          },
        },
        KycApplication: {
          type: "object",
          properties: {
            id: { type: "string" },
            referenceId: { type: "string", example: "PC-KYC-100001" },
            status: {
              type: "string",
              enum: ["pending", "under_review", "approved", "rejected", "revision_requested"],
            },
            investorType: {
              type: "string",
              enum: ["individual", "corporate", "joint"],
              description: "Account opening form type",
            },
            fullName: { type: "string" },
            firstName: { type: "string" },
            fatherName: { type: "string" },
            grandfatherName: { type: "string" },
            phone: { type: "string" },
            email: { type: "string", format: "email" },
            dob: { type: "string", description: "DD/MM/YY" },
            placeOfBirth: { type: "string" },
            gender: { type: "string", enum: ["male", "female", ""] },
            maritalStatus: { type: "string", enum: ["married", "unmarried", "other", ""] },
            nationality: { type: "string" },
            countryOfResidence: { type: "string" },
            residentialStatus: {
              type: "string",
              enum: ["resident", "non_resident", "foreign_national", ""],
            },
            tinNumber: { type: "string" },
            cityAdministration: { type: "string", description: "Region" },
            zone: { type: "string", description: "City / Town" },
            subCity: { type: "string" },
            woredaKebele: { type: "string" },
            houseNumber: { type: "string" },
            tel: { type: "string", description: "Home / office telephone" },
            preferredContact: {
              type: "string",
              enum: ["phone", "email", "online", "in_person", "all"],
            },
            employmentStatus: { type: "string" },
            occupation: { type: "string" },
            employerName: { type: "string" },
            employerAddress: { type: "string" },
            employerPhone: { type: "string" },
            businessName: { type: "string" },
            natureOfBusiness: { type: "string" },
            profession: { type: "string" },
            businessPhone: { type: "string" },
            bankName: { type: "string" },
            bankBranch: { type: "string" },
            accountNumber: { type: "string" },
            accountTitle: { type: "string" },
            settlementOptions: {
              type: "array",
              items: { type: "string", enum: ["pay_to_bank", "pay_to_broker"] },
            },
            idType: { type: "string" },
            idNumber: { type: "string" },
            idIssueDate: { type: "string" },
            idExpiryDate: { type: "string" },
            faydaNumber: { type: "string" },
            faydaIssueDate: { type: "string" },
            faydaExpiryDate: { type: "string" },
            passportNumber: { type: "string" },
            passportIssueDate: { type: "string" },
            passportExpiryDate: { type: "string" },
            kebeleIdNumber: { type: "string" },
            kebeleIssueDate: { type: "string" },
            kebeleExpiryDate: { type: "string" },
            documents: { $ref: "#/components/schemas/KycDocuments" },
            companyName: { type: "string" },
            investorCategory: { type: "string" },
            economicSector: { type: "string" },
            registeredAddress: { type: "string" },
            country: { type: "string" },
            postalCode: { type: "string" },
            registrationNumber: { type: "string" },
            registrationDate: { type: "string" },
            corporateContacts: {
              type: "array",
              items: { $ref: "#/components/schemas/CorporateContact" },
            },
            authorizedSignatoryName: { type: "string" },
            authorizedSignatoryTitle: { type: "string" },
            jointFullName: { type: "string" },
            jointGender: { type: "string" },
            jointMaritalStatus: { type: "string" },
            jointNationality: { type: "string" },
            jointTin: { type: "string" },
            jointDob: { type: "string" },
            jointIdType: { type: "string" },
            jointIdNumber: { type: "string" },
            jointIdIssueDate: { type: "string" },
            jointIdExpiryDate: { type: "string" },
            jointRegion: { type: "string" },
            jointCity: { type: "string" },
            jointSubCity: { type: "string" },
            jointWoredaKebele: { type: "string" },
            jointHouseNumber: { type: "string" },
            jointPhone: { type: "string" },
            jointEmail: { type: "string", format: "email" },
            jointTel: { type: "string" },
            jointResidentialStatus: { type: "string" },
            jointEmploymentStatus: { type: "string" },
            jointEmployerName: { type: "string" },
            jointProfession: { type: "string" },
            jointEmployerAddress: { type: "string" },
            jointBusinessAddress: { type: "string" },
            jointAnnualIncome: { type: "string" },
            jointSourceOfFunds: { type: "string" },
            jointPepStatus: { type: "string", enum: ["yes", "no"] },
            jointPepDetails: { type: "string" },
            sourceOfFunds: { type: "string" },
            annualNetIncome: {
              type: "string",
              enum: ["below_100000", "100000_200000", "200001_500000", "above_500000", ""],
            },
            investmentObjective: {
              type: "array",
              items: {
                type: "string",
                enum: [
                  "capital_preservation",
                  "income",
                  "growth",
                  "trading",
                  "speculation",
                ],
              },
            },
            investmentType: {
              type: "string",
              enum: ["equities", "fixed_income", "both", ""],
            },
            riskTolerance: {
              type: "string",
              enum: ["low", "moderate", "medium", "high", ""],
            },
            ownerType: { type: "string", enum: ["beneficiary", "legal", ""] },
            ownershipCompanies: { type: "array", items: { type: "string" } },
            pepStatus: { type: "string", enum: ["yes", "no"] },
            pepDetails: { type: "string" },
            applicantName: { type: "string" },
            applicantSignature: { type: "string" },
            jointApplicantSignature: { type: "string" },
            dateOfApplication: { type: "string" },
            submitConsent: { type: "boolean" },
            riskDisclosureAck: { type: "boolean" },
            accountCode: { type: "string", description: "For office use only" },
            officeUse: { $ref: "#/components/schemas/OfficeUse" },
            reviewNotes: { type: "string" },
            reviewedBy: { type: "string", nullable: true },
            reviewedAt: { type: "string", format: "date-time", nullable: true },
            submittedAt: { type: "string", format: "date-time" },
            updatedAt: { type: "string", format: "date-time" },
          },
        },
        KycSubmitRequest: {
          type: "object",
          required: ["email", "phone", "submitConsent"],
          properties: {
            investorType: {
              type: "string",
              enum: ["individual", "corporate", "joint"],
              default: "individual",
            },
            fullName: { type: "string" },
            firstName: { type: "string" },
            fatherName: { type: "string" },
            grandfatherName: { type: "string" },
            email: { type: "string", format: "email" },
            phone: { type: "string" },
            dob: { type: "string" },
            gender: { type: "string" },
            maritalStatus: { type: "string" },
            tinNumber: { type: "string" },
            faydaNumber: { type: "string" },
            passportNumber: { type: "string" },
            kebeleIdNumber: { type: "string" },
            companyName: { type: "string" },
            corporateContacts: {
              type: "string",
              description: "JSON string of CorporateContact[]",
            },
            jointFullName: { type: "string" },
            investmentObjective: {
              type: "string",
              description: "JSON array string",
            },
            investmentType: { type: "string" },
            riskTolerance: { type: "string" },
            ownerType: { type: "string" },
            ownershipCompanies: { type: "string", description: "JSON array string" },
            submitConsent: { type: "string", enum: ["true", "false"] },
            riskDisclosureAck: { type: "string", enum: ["true", "false"] },
            faydaFront: { type: "string", format: "binary" },
            faydaBack: { type: "string", format: "binary" },
            kebeleId: { type: "string", format: "binary" },
            drivingLicense: { type: "string", format: "binary" },
            companyStamp: { type: "string", format: "binary" },
          },
        },
        OfficeUseUpdateRequest: {
          type: "object",
          properties: {
            accountCode: { type: "string" },
            preparedBy: { type: "string" },
            preparedSign: { type: "string" },
            preparedDate: { type: "string" },
            approvedBy: { type: "string" },
            approvedSign: { type: "string" },
            approvedDate: { type: "string" },
            checkedBy: { type: "string" },
            checkedSign: { type: "string" },
            checkedDate: { type: "string" },
            officeUse: { $ref: "#/components/schemas/OfficeUse" },
          },
        },
        ApplicationSummary: {
          type: "object",
          properties: {
            id: { type: "string" },
            referenceId: { type: "string" },
            status: { type: "string" },
            firstName: { type: "string" },
            fatherName: { type: "string" },
            email: { type: "string" },
            phone: { type: "string" },
            investorType: { type: "string" },
            submittedAt: { type: "string", format: "date-time" },
          },
        },
        UpdateStatusRequest: {
          type: "object",
          required: ["status"],
          properties: {
            status: {
              type: "string",
              enum: ["pending", "under_review", "approved", "rejected", "revision_requested"],
            },
            reviewNotes: { type: "string" },
          },
        },
        TradeOrder: {
          type: "object",
          properties: {
            id: { type: "string" },
            orderId: { type: "string", example: "PC-ORD-100001" },
            clientName: { type: "string" },
            idNumber: { type: "string", description: "Fayda / ID / Passport" },
            csdAccountNumber: { type: "string" },
            symbol: { type: "string" },
            side: { type: "string", enum: ["BUY", "SELL"] },
            type: { type: "string", enum: ["MARKET", "LIMIT", "STOP", "STOP_LIMIT"] },
            limitPrice: { type: "string" },
            stopPrice: { type: "string" },
            quantity: { type: "string" },
            timeInForce: { type: "string", enum: ["DAY", "GTC", "GTD"] },
            goodTillDate: { type: "string" },
            clientSignature: { type: "string" },
            clientSignatureDate: { type: "string", format: "date", description: "Date next to the client signature" },
            receivedVia: { type: "string", enum: ["In Person", "Neway App"] },
            status: { type: "string", enum: ["Pending", "Accepted", "Rejected"] },
            rejectionReason: { type: "string" },
            traderSignature: { type: "string" },
            receivedBy: { type: "string" },
            dateReceived: { type: "string" },
            timeReceived: { type: "string" },
            createdAt: { type: "string", format: "date-time" },
            updatedAt: { type: "string", format: "date-time" },
          },
        },
        TradeOrderSubmitRequest: {
          type: "object",
          required: [
            "clientName",
            "idNumber",
            "csdAccountNumber",
            "symbol",
            "side",
            "type",
            "quantity",
            "timeInForce",
            "receivedVia",
          ],
          properties: {
            clientName: { type: "string" },
            idNumber: { type: "string" },
            csdAccountNumber: { type: "string" },
            symbol: { type: "string" },
            side: { type: "string", enum: ["BUY", "SELL"] },
            type: { type: "string", enum: ["MARKET", "LIMIT", "STOP", "STOP_LIMIT"] },
            limitPrice: { type: "string" },
            stopPrice: { type: "string" },
            quantity: { type: "string" },
            timeInForce: { type: "string", enum: ["DAY", "GTC", "GTD"] },
            goodTillDate: { type: "string" },
            clientSignature: { type: "string" },
            clientSignatureDate: { type: "string", format: "date" },
            receivedVia: { type: "string", enum: ["In Person", "Neway App"] },
          },
        },
        Stats: {
          type: "object",
          properties: {
            total: { type: "integer" },
            pending: { type: "integer" },
            underReview: { type: "integer" },
            approved: { type: "integer" },
            rejected: { type: "integer" },
            revisionRequested: { type: "integer" },
            rejectionRate: { type: "integer" },
            monthlyApplications: { type: "integer" },
            monthlyVolumeForecast: { type: "number" },
          },
        },
        AuditLog: {
          type: "object",
          properties: {
            id: { type: "string" },
            timestamp: { type: "string", format: "date-time" },
            action: { type: "string" },
            referenceId: { type: "string", nullable: true },
            applicant: { type: "string", nullable: true },
            email: { type: "string", nullable: true },
            previousStatus: { type: "string", nullable: true },
            newStatus: { type: "string", nullable: true },
            reviewedBy: { type: "string", nullable: true },
            notes: { type: "string", nullable: true },
          },
        },
        HealthResponse: {
          type: "object",
          properties: {
            status: { type: "string" },
            service: { type: "string" },
            database: { type: "string" },
            storage: { type: "object" },
            port: { type: "integer" },
          },
        },
      },
    },
    security: [{ bearerAuth: [] }],
    tags: [
      { name: "Health", description: "Health check endpoints" },
      { name: "Auth", description: "Authentication endpoints" },
      { name: "KYC", description: "KYC application submission (Individual, Corporate, Joint)" },
      { name: "Orders", description: "Trade order receiving form" },
      { name: "Admin", description: "Admin management endpoints" },
    ],
  },
  apis: ["./src/routes/*.js"],
};

module.exports = swaggerJsdoc(options);
